module.exports = {
	opening: [
		{ "name": "Fire", "key": "F1" }, // open with fire on off	
		{ "name": "Earth", "key": "F4" }, // open with earth on on
		{ "name": "Eruption", "key": "2"},
		{ "name": "Fire", "key": "F1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Glyph of Storms", "key": "c" },
		{ "name": "Meteor Shower", "key": "5" },
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Conjure Lightning Hammer", "key": "e"},
		{ "name": "Lightning Storm", "key": "4" },
		{ "name": "Auto Attack Chain x2",  "key": "1" },
		{ "name": "Drop Lightning Hammer", "key": "`"},
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Earth", "key": "F4" }, // open with earth on on
		{ "name": "Eruption", "key": "2" },	
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Conjure Fiery Greatsword", "key": "Shift"},
		{ "name": "Fiery Rush", "key": "4" },
		{ "name": "Firestorm", "key": "5" },
		{ "name": "Drop Fiery Greatsword", "key": "`"},
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Fire", "key": "F1" },
		// not an "opener", but apparently not looped over for some reason?
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Firestorm", "key": "c" }, 
		{ "name": "Earth", "key": "F4" },
		{ "name": "Eruption", "key": "2"},
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Meteor Shower", "key": "5" },	
		{ "name": "Fire", "key": "F1" },
	],

	rotation: [
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Earth", "key": "F4" },
		{ "name": "Eruption", "key": "2"},
		/*
			Not necessarily available every rotation
		{ "name": "Conjure Fiery Greatsword", "key": "Shift"},
		{ "name": "Fiery Rush", "key": "4" },
		{ "name": "Firestorm", "key": "5" },
		{ "name": "Drop Fiery Greatsword", "key": "`"},
		*/
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Firestorm", "key": "c" },
		{ "name": "Earth", "key": "F4" },
		{ "name": "Eruption", "key": "2"},
		{ "name": "Meteor Shower", "key": "5" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Conjure Lightning Hammer", "key": "e" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Conjure Lightning Hammer", "key": "e"},
		{ "name": "Lightning Storm", "key": "4" },
		{ "name": "Auto Attack Chain x2",  "key": "1" },
		{ "name": "Drop Lightning Hammer", "key": "`"}
	]
}