module.exports = {
	opening: [
	],

	rotation: [
		{ "name": "Earth", "key": "F4" },
		{ "name": "Eruption", "key": "2"},
		{ "name": "Fire", "key": "F1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Earth", "key": "F4" },
		{ "name": "Meteor Shower", "key": "5" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Conjure Lightning Hammer", "key": "e" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Lightning Storm", "key": "4" },
		{ "name": "Auto Attack Chain (1)",  "key": "1" },
		{ "name": "Auto Attack Chain (2)",  "key": "1" },
		{ "name": "Drop Lightning Hammer", "key": "`"},
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Earth", "key": "F4" },
		{ "name": "Eruption", "key": "2" },
		// if FGS is on cooldown, we skip this section
		{ "name": "(Optional) Conjure Fiery Greatsword", "key": "Shift"},
		{ "name": "Fiery Rush", "key": "4" },
		{ "name": "Firestorm", "key": "5" },
		{ "name": "Drop Fiery Greatsword", "key": "`"},
		{ "name": "Fire", "key": "F1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		// if we are skipping, we would skip to here, change attunement to Fire, then continue from this point
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Meteor Shower", "key": "5" },
		{ "name": "Air", "key": "F3" },
		{ "name": "Glyph of Storms", "key": "c" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Plasma Blast", "key": "3" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Fire", "key": "F1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Conjure Lightning Hammer", "key": "e" },
		{ "name": "Lightning Storm", "key": "4" },
		{ "name": "Auto Attack Chain (1)",  "key": "1" },
		{ "name": "Auto Attack Chain (2)",  "key": "1" },
		{ "name": "Drop Lightning Hammer", "key": "`"},
		{ "name": "Flame Burst", "key": "3" },
		{ "name": "Lava Font", "key": "2" },
		{ "name": "Earth", "key": "F4" },
		{ "name": "Pyroclastic Blast", "key": "3" },
		{ "name": "Eruption", "key": "2"},
		{ "name": "Fire", "key": "F1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Fireball", "key": "1" },
		{ "name": "Lava Font", "key": "2" }
	]
}